import { Users, Flag, Building, Lightbulb } from 'lucide-react';

const questions = [
  {
    id: 1,
    background: "1970년대 초, 당신의 마을에 새마을운동 예산으로 안길 확장 공사가 결정되었습니다. 그런데 문제가 생겼습니다. 공사 노선이 확정되자 땅 일부가 편입되는 지주 3명이 '절대 안 된다'며 강력히 반대하고 나선 것입니다. 이들 없이는 공사를 시작할 수 없고, 설득에 실패하면 마을 전체의 개발이 멈춰버립니다.",
    backgroundEn: "In the early 1970s, a village road expansion project was decided under the Saemaul Movement budget. However, a problem arose. Once the route was finalized, three landowners whose lands were included opposed it strongly, saying 'Absolutely not!' Without their consent, construction cannot start, and if persuasion fails, the development of the entire village will halt.",
    question: "당신이 이 사업을 이끌고 있다면 어떻게 하겠습니까?",
    questionEn: "If you were leading this project, how would you proceed?",
    options: [
      { text: "내 땅을 먼저 조건 없이 내어놓고, 주민들이 보고 느끼도록 기다린다.", 
        textEn: "Donate my own land first unconditionally, and wait for the residents to see and be moved.", 
        type: "LEADER",
        historicalNote: { figure: "새마을지도자 최원규", context: "강원 도원1리", sourceFile: "06_강원도_01_영월군_수주면_도원1리_현대어.md", quote: "대지 100평을 먼저 기증하자, 반대하던 이창노 씨가 스스로 150평을 내놓았습니다." } },
      { text: "이웃들을 한 명씩 찾아다니며 마을 전체가 얻을 이익을 설명한다.", 
        textEn: "Visit neighbors one by one to explain the benefits the entire village will gain.", 
        type: "VILLAGER",
        historicalNote: { figure: "의성군 주민 149명", context: "경북 구담교", sourceFile: "02_대규모사업_경북안동군_풍천면_구담교_현대어.md", quote: "12km나 떨어진 타군 주민들이 '보고만 있을 수 없다'며 삽을 들고 달려왔습니다." } },
      { text: "토지 보상 규정을 검토하고 공정한 절차로 협의에 나선다.", 
        textEn: "Review land compensation regulations and enter negotiations through a fair process.", 
        type: "OFFICIAL",
        historicalNote: { figure: "면장 금중진", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "행정 조율을 통해 IBRD 차관 농로개설 사업 유치에 성공했습니다." } },
      { text: "편입 면적을 최소화하는 대안 노선을 기술적으로 검토해 제안한다.", 
        textEn: "Technically review and propose alternative routes that minimize the affected land area.", 
        type: "EXPERT",
        historicalNote: { figure: "신진토건·CAC 사령부", context: "경북 구담교", sourceFile: "02_대규모사업_경북안동군_풍천면_구담교_현대어.md", quote: "전문 기술 입찰과 군부대 지원으로 3억 공사를 9천만 원에 완성했습니다." } },
    ]
  },
  {
    id: 2,
    background: "마을 앞 강이 매년 범람해 주민들의 논밭을 삼키지만, 다리 하나 없어 학생들은 목숨을 걸고 나룻배를 타야 합니다. 다리 건설 비용은 3억 원. 그러나 군청에서 내려온 예산은 단 3,600만 원뿐입니다. 주민회의에서 '이 돈으론 불가능하다'는 말이 나오자 사람들이 하나둘 자리를 뜨기 시작합니다.",
    backgroundEn: "The river in front of the village floods every year, swallowing up fields, but without a single bridge, students have to risk their lives taking a ferry. The bridge construction costs 300 million KRW. However, the budget allocated from the county office is only 36 million KRW. When someone in the town hall says 'It is impossible with this money,' people start leaving one by one.",
    question: "주민들이 포기하려 합니다. 당신의 첫 번째 행동은?",
    questionEn: "The residents are about to give up. What is your first move?",
    options: [
      { text: "\"할 수 있는 것부터 시작하자!\"며 노동봉사로 강변 골재를 직접 채취하기 시작한다.", 
        textEn: "Say 'Let's start with what we can!' and begin collecting riverbed aggregates ourselves.", 
        type: "LEADER",
        historicalNote: { figure: "대의원 이찬규", context: "경북 구담교", sourceFile: "02_대규모사업_경북안동군_풍천면_구담교_현대어.md", quote: "사재 300만 원을 쾌척하여 구담교 기공의 불씨를 지폈습니다." } },
      { text: "이웃 마을, 다른 군 주민들까지 찾아다니며 십시일반 협력을 구한다.", 
        textEn: "Visit neighboring villages and even other counties to ask for mutual cooperation.", 
        type: "VILLAGER",
        historicalNote: { figure: "부녀노인회 유필규 회장 외 14명", context: "경북 구담교", sourceFile: "02_대규모사업_경북안동군_풍천면_구담교_현대어.md", quote: "평생 모은 관광 적금 15만 원 전액을 기부했습니다. '죽기 전에 다리 놓는 데 보태야 한다'며." } },
      { text: "상급 기관에 차관 사업 유치를 건의하고, 조달청 자재 공급 루트를 탐색한다.", 
        textEn: "Recommend attracting loan projects to higher government levels and explore procurement routes.", 
        type: "OFFICIAL",
        historicalNote: { figure: "군수 문병우", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "\"폭 2m부터 우리 힘으로 뚫어보자\"며 면민 대회를 주재해 주민 동참을 이끌었습니다." } },
      { text: "주민 봉사로 할 부분과 전문 기술 부분을 분리해 공개 입찰 설계를 짠다.", 
        textEn: "Separate community labor parts from technical parts and design an open bidding blueprint.", 
        type: "EXPERT",
        historicalNote: { figure: "도급업자 권태영", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "손실 위기에서도 주민들의 단결에 감동받아 공사 대금 2,500만 원을 조건 없이 기부했습니다." } },
    ]
  },
  {
    id: 3,
    background: "도 농업기술원에서 파견된 기술자가 마을 회관에서 새로운 영농 기술을 소개했습니다. 기존보다 3배 높은 수확량을 낼 수 있다고 하지만, 도입에 필요한 초기 비용과 낯선 방식에 대한 두려움이 있습니다. 마을 어른들은 '검증도 안 된 것을 왜 하냐'며 반신반의하고 있고, 젊은층은 '해보자'는 눈빛입니다.",
    backgroundEn: "A technician dispatched from the Provincial Agricultural Research Center introduced a new farming technology. Although it claims to yield three times more crops, there is fear about the initial costs and unfamiliar methods. The village elders are skeptical, asking 'Why do something unproven?' while the youth look eager to try.",
    question: "이 기술 도입에서 당신의 역할은?",
    questionEn: "What is your role in adopting this new technology?",
    options: [
      { text: "먼저 내 밭에 시범 도입해 위험을 감수하고, 성공하면 이웃들에게 알린다.", 
        textEn: "Adopt it in my own field first to take the risk, and share it with neighbors if successful.", 
        type: "LEADER",
        historicalNote: { figure: "새마을지도자 최원규", context: "강원 도원1리", sourceFile: "06_강원도_01_영월군_수주면_도원1리_현대어.md", quote: "기계화 영농을 직접 도입해 가구당 소득을 30만 원에서 170만 원으로 끌어올렸습니다." } },
      { text: "교육에 적극 참여해 기술을 익히고, 배운 것을 이웃들과 나눈다.", 
        textEn: "Actively participate in training, master the tech, and share it with neighbors.", 
        type: "VILLAGER",
        historicalNote: { figure: "도원1리 주민들", context: "강원 도원1리", sourceFile: "06_강원도_01_영월군_수주면_도원1리_현대어.md", quote: "지게를 영원히 퇴역시키고 경운기 시대를 열어 마을 전체가 함께 풍요로워졌습니다." } },
      { text: "기술 도입에 필요한 교육 프로그램을 기획하고 외부 강사를 섭외한다.", 
        textEn: "Plan education programs necessary for technology adoption and recruit external speakers.", 
        type: "OFFICIAL",
        historicalNote: { figure: "부녀지도자 엄화자", context: "강원 도원1리", sourceFile: "06_강원도_01_영월군_수주면_도원1리_현대어.md", quote: "절미 저축 운동을 조직해 복지회관을 건립하고 부녀 교육의 거점으로 만들었습니다." } },
      { text: "기술의 장단점과 예상 수익성을 데이터로 분석해 마을에 브리핑한다.", 
        textEn: "Analyze the pros and cons along with expected profitability, and brief the village with data.", 
        type: "EXPERT",
        historicalNote: { figure: "구담교 기술진", context: "경북 구담교", sourceFile: "02_대규모사업_경북안동군_풍천면_구담교_현대어.md", quote: "전문 분야 입찰 설계로 토지 가치 18억 8천만 원 상승 효과를 만들어냈습니다." } },
    ]
  },
  {
    id: 4,
    background: "공사 방식을 두고 주민들이 두 패로 나뉘었습니다. 한쪽은 '우리 손으로 직접 하자', 다른 쪽은 '전문 업체에 맡겨야 한다'며 총회 중간에 고성이 오갑니다. 회의장 분위기는 싸늘하게 얼어붙었고, 서로 등을 돌리기 일보 직전입니다. 이대로라면 사업 자체가 무산될 수도 있습니다.",
    backgroundEn: "The residents are split into two factions regarding the construction method. One side shouts 'Let's do it with our own hands,' while the other side insists 'We must hire professional contractors.' Cold tension fills the hall, and they are on the verge of turning away from each other. If this continues, the project itself may fall through.",
    question: "당신은 어떻게 대처합니까?",
    questionEn: "How do you handle this confrontation?",
    options: [
      { text: "마을 전체의 발전을 위한 절충안을 강력하게 제시한다.", 
        textEn: "Strongly propose a compromise plan designed for the progress of the entire village.", 
        type: "LEADER",
        historicalNote: { figure: "추진위원장 문학구", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "사기가 바닥에 떨어진 주민들 앞에서 즉석 연설로 불씨를 다시 살렸습니다." } },
      { text: "이웃 간의 공동체 의식을 강조하며 분위기를 부드럽게 풀어낸다.", 
        textEn: "Emphasize mutual community bonds to soften the frozen atmosphere.", 
        type: "VILLAGER",
        historicalNote: { figure: "구담 2동 부녀회", context: "경북 구담교", sourceFile: "02_대규모사업_경북안동군_풍천면_구담교_현대어.md", quote: "품앗이와 상부상조 정신으로 분열된 마을을 하나로 묶어냈습니다." } },
      { text: "객관적 중재자로서 회의 규칙을 상기시키고 공정한 발언 기회를 준다.", 
        textEn: "Act as an objective mediator, remind them of rules, and give everyone a fair chance to speak.", 
        type: "OFFICIAL",
        historicalNote: { figure: "면장 구재우", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "1,021명의 서명을 조직화해 공식 진정으로 사업을 채택시켰습니다." } },
      { text: "갈등 원인이 된 문제의 정확한 사실과 대안을 냉철하게 제시한다.", 
        textEn: "Coolly present precise facts and structural alternatives related to the source of conflict.", 
        type: "EXPERT",
        historicalNote: { figure: "돗재도로 효과 분석", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "42km 우회로가 6km로 단축된 수치 하나가 모든 반대 여론을 잠재우는 힘을 갖고 있습니다." } },
    ]
  },
  {
    id: 5,
    background: "234일간의 피와 땀 끝에 드디어 마을 개발 프로젝트가 완료되었습니다. 개통식 날, 연인원 45,000명이 함께 만들어낸 결실 앞에 서 있습니다. 어떤 이는 눈물을 훔치고, 어떤 이는 환호를 지릅니다. 당신은 그 자리에서 어떤 순간에 가장 깊은 뿌듯함을 느꼈나요?",
    backgroundEn: "After 234 days of blood, sweat, and tears, the village development project is finally completed. On opening day, you stand in front of the milestone built by 45,000 cumulative workers. Some wipe tears, and others cheer. In what moment do you feel the deepest fulfillment?",
    question: "당신이 가장 뿌듯함을 느끼는 순간은?",
    questionEn: "When do you feel the most proud?",
    options: [
      { text: "사람들이 내 비전을 믿고, 끝까지 함께 땀 흘려준 것을 볼 때.", 
        textEn: "When I see that people trusted my vision and sweat together with me until the end.", 
        type: "LEADER",
        historicalNote: { figure: "추진위원장 문학구", context: "전남 한천면 돗재도로", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "연인원 45,000명이 234일간 함께 땀 흘려 해발 350m 준령을 뚫었습니다." } },
      { text: "마을이 살기 좋아지고 이웃들의 얼굴에 웃음꽃이 필 때.", 
        textEn: "When the village becomes a better place to live and smiles bloom on neighbors' faces.", 
        type: "VILLAGER",
        historicalNote: { figure: "한천면민 일동", context: "전남 한천면 돗재도로", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "\"피땀 흘려 쌓아 올린 이 영광의 금자탑을 자손만대에 전합니다.\" — 돗재 기념비문" } },
      { text: "행정 지원과 조율이 제 역할을 해 프로젝트가 무사히 완료되었을 때.", 
        textEn: "When administrative coordination functioned properly and the project finished safely.", 
        type: "OFFICIAL",
        historicalNote: { figure: "화순군수 문병우", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "행정·재정·기술을 총동원한 결과, IBRD 차관 사업으로 정식 전천후 도로가 완성되었습니다." } },
      { text: "내가 기획한 전략대로 오차 없이 완벽한 결과물이 도출되었을 때.", 
        textEn: "When a perfect result is produced exactly according to my planned strategy without error.", 
        type: "EXPERT",
        historicalNote: { figure: "도급업자 권태영", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "설계·시공·마무리 모두 완벽하게 마감되어 면민들로부터 감사패를 받았습니다." } },
    ]
  },
  {
    id: 6,
    background: "6개월간 연인원 2만 명이 피땀을 흘려 쌓아 올린 절개지 10,000㎡가 하룻밤 폭우로 무너져 내렸습니다. 새벽 4시, 현장에 달려온 주민들이 무너진 흙더미 앞에서 주저앉아 울고 있습니다. '이젠 끝이다'는 말이 새어 나오고, 새벽하늘 아래 모두의 눈빛에서 희망이 사라지고 있습니다.",
    backgroundEn: "The 10,000㎡ cut slope, built with the blood and sweat of 20,000 cumulative workers over 6 months, collapsed overnight due to heavy rain. At 4 AM, residents who rushed to the site sit down and weep in front of the pile of dirt. Whispers of 'It is all over' emerge, and hope disappears under the morning sky.",
    question: "당신이라면 어떻게 하겠습니까?",
    questionEn: "What would you do in this situation?",
    options: [
      { text: "산봉우리에 천막을 치고 밤새 현장을 지키며, 횃불 야간 재건 작업을 이끈다.", 
        textEn: "Set up a tent on the hilltop, watch the site all night, and lead reconstruction with torches.", 
        type: "LEADER",
        historicalNote: { figure: "문학구 위원장·금중진 면장", context: "전남 한천면 돗재도로", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "산봉우리 천막에서 밤이슬을 맞으며 현장을 지키고, 수백 개 횃불로 야간 재건을 이끌었습니다." } },
      { text: "주저앉은 주민들 곁에 앉아 함께 울어주고, 손을 잡으며 내일부터 다시 시작하자고 한다.", 
        textEn: "Sit down beside weeping residents, weep together, and hold hands to start again tomorrow.", 
        type: "VILLAGER",
        historicalNote: { figure: "한천면 주민들", context: "전남 한천면 돗재도로", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "기상특보마다 한밤중에도 횃불을 들고 달려나와 장비와 자갈을 함께 지켜냈습니다." } },
      { text: "피해 현황을 집계하여 복구 지원금을 신청하고 긴급 지원을 요청한다.", 
        textEn: "Assess damage details, apply for restoration funding, and request emergency assistance.", 
        type: "OFFICIAL",
        historicalNote: { figure: "군수 문병우", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "공사 위기마다 행정 루트를 총동원해 군부대 중장비 지원과 IBRD 차관을 이끌어냈습니다." } },
      { text: "붕괴 원인을 분석하고, 반복되지 않도록 개선된 설계와 공법을 제안한다.", 
        textEn: "Analyze the cause of collapse, and propose improved designs and construction methods.", 
        type: "EXPERT",
        historicalNote: { figure: "CAC 사령부", context: "전남 한천면 돗재도로", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "페이로더·에어 콤프레셔·불도저를 투입해 22일간 천운산 암벽 발파를 완수했습니다." } },
    ]
  },
  {
    id: 7,
    background: "마을 개발 사업에 '결사반대'를 외치는 핵심 반대파 1인이 있습니다. 그는 마을회관 앞에 현수막까지 걸고, 다른 주민들을 찾아다니며 반대 서명을 받으러 다닙니다. 그와 대화 한번 나눠보기로 했습니다. 어떻게 접근하시겠습니까?",
    backgroundEn: "There is one core opposer shouting 'Desperate Opposition!' to the village project. He even hung banners in front of the town hall and visits other residents to collect opposing signatures. You decided to talk with him. How will you approach?",
    question: "당신의 설득 방식은?",
    questionEn: "What is your persuasion strategy?",
    options: [
      { text: "말보다는 행동으로 먼저 희생하여 상대방 양심에 호소한다.", 
        textEn: "Sacrifice by action first rather than words, appealing to their conscience.", 
        type: "LEADER",
        historicalNote: { figure: "새마을지도자 최원규", context: "강원 도원1리", sourceFile: "06_강원도_01_영월군_수주면_도원1리_현대어.md", quote: "대지 100평 선제 기증 → 이창노(150평)·이운세(190평) 연쇄 동참. 희생이 반대를 녹였습니다." } },
      { text: "반대하는 이유를 진심으로 들어주고 공감하며 천천히 관계를 쌓는다.", 
        textEn: "Listen sincerely to their reasons, empathize, and build a relationship slowly.", 
        type: "VILLAGER",
        historicalNote: { figure: "부녀지도자 엄화자", context: "강원 도원1리", sourceFile: "06_강원도_01_영월군_수주면_도원1리_현대어.md", quote: "절미 저축 운동으로 주민 신뢰를 쌓아, 폭력적이던 마을 풍습을 온전히 바꿔냈습니다." } },
      { text: "이해관계를 분석하여 공정한 조건과 절차로 공식 합의를 이끈다.", 
        textEn: "Analyze mutual interests and lead a formal agreement with fair terms and procedures.", 
        type: "OFFICIAL",
        historicalNote: { figure: "면장 구재우", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "수백 명의 서명을 정식 진정으로 조직화해 불가능하다던 사업을 정부가 채택하게 만들었습니다." } },
      { text: "반대 근거를 반박할 객관적 데이터와 성공 사례를 체계적으로 제시한다.", 
        textEn: "Systematically present objective data and success stories to counter their claims.", 
        type: "EXPERT",
        historicalNote: { figure: "돗재도로 성과 수치", context: "전남 한천면", sourceFile: "01_대규모사업_전남화순군_한천면_돗재도로_현대어.md", quote: "42km→6km 단축, 소득 5.6배 증가. 숫자는 그 어떤 말보다 강력했습니다." } },
    ]
  },
];

const resultsData = {
  LEADER: {
    title: "열정의 불꽃, 솔선수범의 아이콘",
    titleEn: "Flame of Passion, Icon of Leading by Example",
    role: "새마을지도자 (Saemaul Leader)",
    roleEn: "Saemaul Leader",
    icon: Flag,
    color: "bg-orange-500", lightColor: "bg-orange-50", textColor: "text-orange-600", borderColor: "border-orange-200",
    description: "당신은 아무도 가지 않은 길을 가장 먼저 걷는 개척자입니다. 말보다는 행동으로, 지시보다는 솔선수범으로 사람들의 마음을 움직이는 진정한 리더입니다.\n\n당신 같은 유형의 사람은 불가능해 보이는 목표 앞에서도 흔들리지 않습니다. 희생이 필요하다면 먼저 자신의 것을 내어놓고, 위험을 감수해야 한다면 가장 앞장서서 나아갑니다. 포기가 전염되듯, 용기도 전염됩니다. 당신의 한 걸음이 마을 전체를 움직이는 진원이 됩니다.\n\n강점으로는 강한 추진력과 결단력, 구성원을 감화시키는 행동력이 있습니다. 다만 때로는 속도를 늦추고 주변의 의견을 더 경청하는 것이 더 오래 함께 가는 길이 되기도 합니다.",
    descriptionEn: "You are a pioneer who walks the path no one else has trodden. A true leader who moves people's hearts by action rather than words, by leading by example rather than giving directions.\n\nPeople of your type do not shake in front of seemingly impossible goals. If sacrifice is needed, you donate yours first, and if danger must be faced, you lead the way. Like giving up, courage is contagious. Your single step becomes the epicenter moving the whole village.\n\nYour strengths include strong drive, decisiveness, and inspiring action. However, slowing down and listening to the opinions around you can sometimes be the key to going further together.",
    historicalCase: {
      title: "강원 도원1리 — 100평 선제 기증으로 반대를 녹이다",
      titleEn: "Dowon 1-ri, Gangwon — Melting Opposition with 100-pyeong Land Donation",
      content: "강원도 영월군 수주면 도원1리의 새마을지도자 최원규는 마을 안길 확장에 극심하게 반대하던 주민들을 설득하기 위해 먼저 자신의 대지 100평을 조건 없이 기증했습니다. 그러자 강력히 반대하던 이창노 씨가 스스로 150평을, 이운세 씨가 190평을 기꺼이 내놓았습니다. '희생이 반대를 녹인다'는 솔선수범의 원리가 가장 극적으로 증명된 순간이었습니다. 최원규 지도자는 이후에도 기계화 영농을 직접 자신의 밭에 먼저 도입하여 가구당 소득을 30만 원에서 170만 원으로 끌어올렸습니다.",
      contentEn: "Saemaul Leader Choi Won-gyu of Dowon 1-ri, Yeongwol-gun, Gangwon-do, donated 100 pyeong of his own land unconditionally to persuade residents strongly opposing the village road widening. Following this, the strongest opponent Lee Chang-no voluntarily donated 150 pyeong, and Lee Un-se donated 190 pyeong. It was a dramatic proof of the principle of leading by example. Leader Choi later introduced mechanized farming to his own fields first, increasing average household income from 300,000 KRW to 1.7 million KRW."
    },
    traits: ["강력한 추진력", "자기 희생", "비전 제시", "설득의 달인"],
    traitsEn: ["Strong Drive", "Self-Sacrifice", "Vision Presentation", "Persuasion Master"],
    quote: "뜻이 있는 곳에 반드시 길이 있습니다. 내가 먼저 움직이면 세상이 따라옵니다.",
    quoteEn: "Where there is a will, there is a way. When I move first, the world follows.",
    representativeFigure: "문학구 추진위원장 · 최원규 새마을지도자",
    representativeFigureEn: "Chairman Moon Hak-gu · Saemaul Leader Choi Won-gyu",
    representativeContext: "전남 한천면 돗재도로 · 강원 도원1리",
    representativeContextEn: "Hwasun Dotjae Road, Jeonnam · Dowon 1-ri, Gangwon",
  },
  VILLAGER: {
    title: "함께 걷는 동반자, 공동체의 심장",
    titleEn: "Companion walking together, Heart of Community",
    role: "마을주민 (Villager)",
    roleEn: "Villager",
    icon: Users,
    color: "bg-emerald-500", lightColor: "bg-emerald-50", textColor: "text-emerald-600", borderColor: "border-emerald-200",
    description: "당신은 새마을운동의 가장 강력한 원동력입니다. 이웃과 협력하고 땀 흘려 일하며 기적을 현실로 만드는 진정한 실천가입니다.\n\n당신 같은 유형의 사람은 혼자 앞에 서기보다 서로의 어깨를 기대며 함께 걷는 것에서 가장 큰 힘을 발휘합니다. 이웃의 아픔에 공감하고, 마을 전체의 문제를 나의 문제로 받아들이는 따뜻한 공동체 의식이 당신의 가장 큰 자산입니다. 새마을운동의 역사에서 실제로 가장 많은 기적을 만들어낸 것은 바로 당신과 같은 평범한 주민들의 뜨거운 헌신이었습니다.\n\n강점은 높은 공감 능력, 지속적인 실천력, 그리고 이웃을 하나로 묶는 포용력입니다. 다만 때로는 리더가 없을 때 방향을 잃기 쉬우므로, 스스로 작은 결정이라도 이끌어 보는 연습이 필요할 수 있습니다.",
    descriptionEn: "You are the strongest driving force of the Saemaul Movement. A true practitioner who cooperates with neighbors, sweats together, and turns miracles into reality.\n\nInstead of standing alone in front, a person of your type exerts the greatest strength when walking shoulder-to-shoulder with others. Empathizing with neighbors' pain and accepting the village's problems as your own is your greatest asset. In the history of the Saemaul Movement, most miracles were built by the warm devotion of ordinary villagers like you.\n\nYour strengths include high empathy, consistent execution, and inclusive power that unites neighbors. However, you might lose direction easily when a leader is absent, so practicing leading small decisions on your own could be helpful.",
    historicalCase: {
      title: "경북 구담교 — 평생의 적금을 내어놓은 노인의 마음",
      titleEn: "Gudam Bridge, Gyeongbuk — The Heart of an Elder Donating Lifetime Savings",
      content: "경북 안동군 풍천면 구담교 건설 당시, 부녀노인회장 유필규 씨는 평생 모아온 관광 적금 15만 원 전액을 기부했습니다. '죽기 전에 다리 놓는 데 보태야 한다'는 말 한 마디였습니다. 12km나 떨어진 의성군의 주민 149명도 '보고만 있을 수 없다'며 삽을 들고 달려왔습니다. 이처럼 마을주민 유형은 거창한 계획이 아닌, 이웃에 대한 진심 어린 마음으로 가장 큰 기적을 만들어냅니다.",
      contentEn: "During the construction of Gudam Bridge in Pungcheon-myeon, Andong-gun, Gyeongbuk, Elder Yu Pil-gyu donated 150,000 KRW, his entire savings for a lifetime travel fund, saying, 'I must contribute to building the bridge before I die.' Hearing this, 149 residents from Uiseong-gun, 12km away, ran over with shovels, saying 'We cannot just watch.' Villagers create the greatest miracles through sincere hearts, not grand plans."
    },
    traits: ["강한 협동심", "성실한 실천", "공동체 의식", "포용력"],
    traitsEn: ["Strong Cooperation", "Diligence", "Community Bond", "Inclusiveness"],
    quote: "백지장도 맞들면 낫습니다. 우리가 조금씩 보태면 못 할 것이 없습니다.",
    quoteEn: "Many hands make light work. There is nothing we cannot do if we combine our efforts.",
    representativeFigure: "부녀노인회 유필규 회장 · 의성군 최청웅 동장",
    representativeFigureEn: "Elder Yu Pil-gyu · Chief Choi Cheong-ung",
    representativeContext: "경북 구담교 건설",
    representativeContextEn: "Gudam Bridge Construction, Gyeongbuk",
  },
  OFFICIAL: {
    title: "든든한 지원군, 공정한 중재자",
    titleEn: "Reliable Supporter, Fair Mediator",
    role: "공무원 (Public Official)",
    roleEn: "Public Official",
    icon: Building,
    color: "bg-blue-500", lightColor: "bg-blue-50", textColor: "text-blue-600", borderColor: "border-blue-200",
    description: "당신은 보이지 않는 곳에서 무대를 세우는 든든한 기둥입니다. 자원을 배분하고, 제도를 정비하며, 갈등을 중재하여 사람들의 열정이 실질적인 성과로 이어지게 하는 연결의 달인입니다.\n\n당신 같은 유형의 사람은 감정적으로 움직이기보다 규칙과 절차 안에서 가장 합리적인 길을 찾습니다. 수백 명의 이해관계를 조율하고, 외부 자원을 끌어오며, 법과 행정의 언어로 꿈을 현실로 번역하는 역할을 합니다. 리더가 불꽃을 일으키고 주민이 연료를 공급한다면, 당신은 그 에너지를 한 방향으로 집중시키는 통로입니다.\n\n강점은 체계적인 문제 해결, 자원 조달 능력, 공정한 중재력입니다. 때로는 유연성 부족이나 결정의 지연이 약점이 될 수 있으나, 당신이 없다면 아무리 훌륭한 열정도 체계 없이 흩어지고 맙니다.",
    descriptionEn: "You are a reliable pillar setting the stage behind the scenes. A master of connection who allocates resources, organizes systems, and mediates conflicts to turn people's passion into actual achievements.\n\nInstead of acting emotionally, a person of your type finds the most rational path within rules and procedures. You coordinate the interests of hundreds, draw external resources, and translate dreams into reality through administrative language. If leaders spark the flame and villagers supply fuel, you are the conduit focusing that energy.\n\nYour strengths include systematic problem solving, resource acquisition, and fair mediation. Sometimes a lack of flexibility or delayed decisions can be a weakness, but without you, grand passion scatters without structure.",
    historicalCase: {
      title: "전남 한천면 — 1,021명의 서명으로 불가능을 뒤집다",
      titleEn: "Hancheon-myeon, Jeonnam — Overturning Impossibility with 1,021 Signatures",
      content: "전남 화순군 한천면 면장 구재우는 주민들의 반발을 무릅쓰고 1,021명의 주민 서명을 조직화해 정식 진정서를 제출했습니다. 행정 루트를 통해 IBRD(세계은행) 차관 사업을 유치하는 데 성공했고, 군수 문병우는 공사 위기 때마다 군부대 중장비 지원과 긴급 행정 지원을 이끌어냈습니다. 주민의 열정만으로는 넘을 수 없었던 벽을 행정의 힘으로 허문 것입니다.",
      contentEn: "Chief Gu Jae-u of Hancheon-myeon, Hwasun-gun, Jeonnam, organized 1,021 resident signatures to submit a formal petition despite pushback. He successfully attracted IBRD loan projects, and County Governor Moon Byung-woo secured military equipment support and urgent administrative aid during construction crises. The wall that residents' passion alone could not climb was broken by administrative power."
    },
    traits: ["체계적 지원", "자원 관리", "공정함", "행정적 조율"],
    traitsEn: ["Systematic Support", "Resource Management", "Fairness", "Administrative Coordination"],
    quote: "여러분의 열정을 행정으로 든든하게 뒷받침하겠습니다.",
    quoteEn: "I will firmly support your passion through administration.",
    representativeFigure: "면장 금중진 · 군수 문병우",
    representativeFigureEn: "Chief Geum Jung-jin · Governor Moon Byung-woo",
    representativeContext: "전남 한천면 돗재도로 개설",
    representativeContextEn: "Hwasun Dotjae Road Construction, Jeonnam",
  },
  EXPERT: {
    title: "냉철한 전략가, 지식의 등대",
    titleEn: "Cool-headed Strategist, Lighthouse of Knowledge",
    role: "전문가 (Expert)",
    roleEn: "Expert",
    icon: Lightbulb,
    color: "bg-purple-500", lightColor: "bg-purple-50", textColor: "text-purple-600", borderColor: "border-purple-200",
    description: "당신은 직관보다는 데이터와 분석을 믿는 지식인입니다. 한정된 자원으로 최고의 효율을 낼 수 있도록 과학적인 해결책을 제시하는 전략가입니다.\n\n당신 같은 유형의 사람은 감정보다 숫자를 신뢰하고, 경험보다 검증된 방법론을 선호합니다. 문제의 본질을 분석하고, 최선의 해결 경로를 설계하며, 복잡한 상황을 단순하고 명쾌한 논리로 정리합니다. 새마을운동에서도 기술 전문가와 외부 협력사의 과학적 접근이 없었다면 3억 원짜리 교량을 9천만 원에 건설하는 기적은 불가능했을 것입니다.\n\n강점은 객관적 분석력, 효율적 자원 배분, 기술적 통찰력입니다. 다만 지나친 논리 중심의 접근은 사람의 마음을 얻는 데 한계가 될 수 있으므로, 데이터와 인간적 공감을 함께 활용하는 균형이 중요합니다.",
    descriptionEn: "You are an intellectual who trusts data and analysis over intuition. A strategist who provides scientific solutions to achieve maximum efficiency with limited resources.\n\nYou trust numbers over emotions and prefer proven methodologies over subjective experiences. You analyze the essence of problems, design the best path for solutions, and simplify complex situations with clear logic. In the Saemaul Movement, without technical experts and scientific approaches, the miracle of building a 300 million KRW bridge with only 90 million KRW would have been impossible.\n\nYour strengths include objective analysis, efficient resource allocation, and technical insight. However, an excessively logic-driven approach has limits in winning hearts, so balance using both data and human empathy.",
    historicalCase: {
      title: "경북 구담교 — 3억 공사를 9천만 원에 완성한 설계의 힘",
      titleEn: "Gudam Bridge, Gyeongbuk — The Power of Design completing 300M KRW construction with 90M",
      content: "경북 안동군 구담교 건설에서 도급업자 권태영과 CAC 사령부는 전문 기술 입찰과 군부대 장비를 체계적으로 활용하여 당초 3억 원이 필요하던 교량 공사를 9천만 원에 완성시켰습니다. 단순한 절감이 아니라, 정확한 공정 설계와 자재 분석, 그리고 각 단계별 전문가 투입 계획이 만들어낸 결과였습니다. 전문가 유형은 '42km 우회로를 6km로 단축한다'는 숫자 하나로 모든 반대 여론을 잠재우는 힘을 갖고 있습니다.",
      contentEn: "In the Gudam Bridge construction in Andong-gun, Gyeongbuk, contractor Kwon Tae-young and the CAC Command systematically utilized professional bidding and military equipment to complete a bridge construction, originally budgeted at 300 million KRW, for just 90 million KRW. This was not a simple discount, but the result of precise process design, material analysis, and expert deployment. Expert archetypes hold the power to silence opposition with a single number, like 'reducing a 42km detour to 6km.'"
    },
    traits: ["데이터 분석", "효율성 추구", "객관적 시각", "기술적 조언"],
    traitsEn: ["Data Analysis", "Efficiency Drive", "Objective View", "Technical Advice"],
    quote: "정확한 분석 및 효율적인 설계가 불가능을 가능으로 바꿉니다.",
    quoteEn: "Accurate analysis and efficient design turn the impossible into possible.",
    representativeFigure: "도급업자 권태영 · CAC 사령부",
    representativeFigureEn: "Contractor Kwon Tae-young · CAC Command",
    representativeContext: "전남 한천면 돗재도로 · 경북 구담교",
    representativeContextEn: "Hwasun Dotjae Road, Jeonnam · Gudam Bridge, Gyeongbuk",
  },
};

export { questions, resultsData };
